apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kanban-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hanadisa/aks-gitops-kanban
    targetRevision: main
    path: k8s-manifests/kanban-app
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
