prometheus:
  enabled: true
  service:
    type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: "nginx"
    annotations:
      nginx.org/hsts: "true"
      cert-manager.io/cluster-issuer: issuer
    hosts:
      - prometheus.203.0.113.10.nip.io
    tls:
      - secretName: prometheus-ingress-tls
        hosts:
          - prometheus.203.0.113.10.nip.io

grafana:
  enabled: true
  adminUser: admin
  adminExistingSecret: grafana-admin-password
  adminPasswordKey: admin-password
  service:
    type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: "nginx"
    annotations:
      nginx.org/hsts: "true"
      cert-manager.io/cluster-issuer: issuer
    hosts:
      - grafana.203.0.113.10.nip.io
    tls:
      - secretName: grafana-ingress-tls
        hosts:
          - grafana.203.0.113.10.nip.io
  persistence:
    enabled: true
    size: 10Gi


prometheus-node-exporter:
  hostPort:
    enabled: false

kubeStateMetrics:
  enabled: true

alertmanager:
  enabled: true
  alertmanagerSpec:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 200m
        memory: 512Mi
