name: Build, Scan & Push App Image

on:
  push:
    branches:
      - dev

jobs:
  build-scan-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      security-events: write

    defaults:
      run:
        working-directory: "./app/" 

    env:
      ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
      ACR_NAME: kanbanacr
      IMAGE_NAME: kanban-app 
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .
          docker build -t ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest .

      - name: Run Trivy vulnerability scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          format: 'sarif'
          output: 'trivy-results.sarif'
          exit-code: '0'
          severity: 'HIGH,CRITICAL'
        env: 
          TRIVY_USERNAME: ${{ secrets.AZURE_CLIENT_ID }} 
          TRIVY_PASSWORD: ${{ secrets.AZURE_CLIENT_SECRET }} 
          TRIVY_AUTH_URL: ${{ env.ACR_LOGIN_SERVER }} 

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
          wait-for-processing: true

      - name: Push Docker Image to ACR
        run: |
          az acr login --name ${{ env.ACR_NAME }}
          docker push ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          docker push ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest