name: Terraform Apply

on:
  push:
    branches:
      - dev

jobs:
  terraformapply:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./terraform/"

    permissions:
      id-token: write
      contents: read
      pull-requests: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Download terraform.tfvars from Azure Blob Storage
        run: |
          az storage blob download \
            --account-name rmttfstatehanad \
            --container-name tfstate \
            --name terraform.tfvars \
            --file terraform.tfvars \
            --auth-mode login
        shell: bash

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve