name: Terraform Destroy

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  terraformdestroy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./terraform/"  

    env:
      storage_account_name: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
      container_name: ${{ secrets.AZURE_CONTAINER_NAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Download terraform.tfvars from Azure Blob Storage
        run: |
          az storage blob download \
            --account-name ${{ env.storage_account_name }} \
            --container-name ${{ env.container_name }} \
            --name terraform.tfvars \
            --file terraform.tfvars \
            --auth-mode login
        shell: bash

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
