name: Terraform Destroy

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  terraformdestroy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./terraform/"

    permissions:
      id-token: write
      contents: read
      pull-requests: write

    env:
      RESOURCE_GROUP_NAME: ${{ secrets.RESOURCE_GROUP_NAME }}
      STORAGE_ACCOUNT_NAME: ${{ secrets.STORAGE_ACCOUNT_NAME }}
      CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
      BACKEND_KEY: terraform.tfstate
      KUBECONFIG: ~/.kube/config
      CLUSTER_NAME: ${{ secrets.AKS_CLUSTER_NAME }}
      TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Download terraform.tfvars from Azure Blob Storage
        run: |
          az storage blob download \
            --account-name $STORAGE_ACCOUNT_NAME \
            --container-name $CONTAINER_NAME \
            --name terraform.tfvars \
            --file terraform.tfvars \
            --auth-mode login
        shell: bash

      - name: Get AKS Credentials
        run: |
          az aks get-credentials --resource-group $RESOURCE_GROUP_NAME --name $CLUSTER_NAME
        shell: bash

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.1

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="resource_group_name=$RESOURCE_GROUP_NAME" \
            -backend-config="storage_account_name=$STORAGE_ACCOUNT_NAME" \
            -backend-config="container_name=$CONTAINER_NAME" \
            -backend-config="key=$BACKEND_KEY" \
            -backend-config="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
            -backend-config="tenant_id=${{ secrets.AZURE_TENANT_ID }}" \
            -var="ssh_public_key_data=${{ secrets.SSH_PUBLIC_KEY_AKS }}"
        shell: bash

      - name: Terraform Destroy
        run: |
          terraform destroy -auto-approve \
            -var="ssh_public_key_data=${{ secrets.SSH_PUBLIC_KEY_AKS }}"
        shell: bash

