name: Terraform Destroy

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  terraformdestroy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./terraform/"

    permissions:
      id-token: write
      contents: read
      pull-requests: write

    env:
      RESOURCE_GROUP_NAME: rg-aks-kanban
      STORAGE_ACCOUNT_NAME: rmttfstatehanad
      CONTAINER_NAME: tfstate
      BACKEND_KEY: terraform.tfstate
      TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="resource_group_name=${{ env.RESOURCE_GROUP_NAME }}" \
            -backend-config="storage_account_name=${{ env.STORAGE_ACCOUNT_NAME }}" \
            -backend-config="container_name=${{ env.CONTAINER_NAME }}" \
            -backend-config="key=${{ env.BACKEND_KEY }}"

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
