name: Terraform Destroy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  terraformdestroy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform

    permissions:
      id-token: write
      contents: read
      pull-requests: write

    env:
      RESOURCE_GROUP_NAME: rg-aks-kanban
      STORAGE_ACCOUNT_NAME: rmttfstatehanad
      CONTAINER_NAME: tfstate
      BACKEND_KEY: terraform.tfstate
      TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.1

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="resource_group_name=${{ env.RESOURCE_GROUP_NAME }}" \
            -backend-config="storage_account_name=${{ env.STORAGE_ACCOUNT_NAME }}" \
            -backend-config="container_name=${{ env.CONTAINER_NAME }}" \
            -backend-config="key=${{ env.BACKEND_KEY }}" \
            -backend-config="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
            -backend-config="tenant_id=${{ secrets.AZURE_TENANT_ID }}"

      - name: Terraform Force Unlock (if needed)
        run: |
          echo yes | terraform force-unlock 9b56ad61-ad74-8504-0454-18e3817d009e || echo "No lock found or already released"

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -parallelism=1
