name: Terraform Plan 

on:
  push:
    branches: [dev]
    paths:
      - 'terraform/**'
      - '.github/workflows/tf-plan.yml'
  pull_request:
    branches: [dev]
    paths:
      - 'terraform/**'
      - '.github/workflows/tf-plan.yml'

permissions:
  contents: read
  security-events: write
  id-token: write
  pull-requests: write

env:
  RESOURCE_GROUP_NAME: ${{ secrets.RESOURCE_GROUP_NAME }}
  STORAGE_ACCOUNT_NAME: ${{ secrets.STORAGE_ACCOUNT_NAME }}
  CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
  TFSTATE_KEY: ${{ secrets.TFSTATE_KEY }}

jobs:
  terraformplan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login (SP)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="resource_group_name=${{ env.RESOURCE_GROUP_NAME }}" \
            -backend-config="storage_account_name=${{ env.STORAGE_ACCOUNT_NAME }}" \
            -backend-config="container_name=${{ env.CONTAINER_NAME }}" \
            -backend-config="key=${{ env.TFSTATE_KEY }}"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: |
          terraform plan -input=false -no-color > plan_output.txt
          cat plan_output.txt

      - name: Checkov Scan
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          framework: terraform
          output_format: cli,sarif
          output_file_path: checkov-results-terraform.sarif
        continue-on-error: true

      - name: Upload Checkov SARIF to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: './terraform/checkov-results-terraform.sarif'
